name: pgmcp
services:
  postgres:
    image: docker.io/postgres:17.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dvdrental
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seed:/seed:ro
      - ./seed/seed.sh:/docker-entrypoint-initdb.d/seed.sh:ro
    
volumes:
  pgdata: {}
